Repository googleapis/nodejs-spanner, pull requests merged in 2018-03, with the labels that each got.

#132 feature: batch queries
  protos/google/spanner/v1/spanner.proto
  samples/batch.js
  samples/system-test/spanner.test.js
  src/batch-transaction.js
  src/codec.js
  src/database.js
  src/index.js
  src/transaction-request.js
  src/v1/spanner_client.js
  src/v1/spanner_client_config.json
  test/batch-transaction.js
  test/codec.js
  test/database.js
  test/index.js
  test/transaction-request.js
Labels: cla: yes

#136 Cleanup Spanner region tags.
  samples/crud.js
  samples/indexing.js
  samples/schema.js
  samples/transaction.js
  src/database.js
  src/instance.js
  src/table.js
Labels: cla: no

#137 Regenerate gapic
  protos/google/spanner/admin/database/v1/spanner_database_admin.proto
  protos/google/spanner/admin/instance/v1/spanner_instance_admin.proto
  protos/google/spanner/v1/keys.proto
  protos/google/spanner/v1/mutation.proto
  protos/google/spanner/v1/query_plan.proto
  protos/google/spanner/v1/result_set.proto
  protos/google/spanner/v1/spanner.proto
  protos/google/spanner/v1/transaction.proto
  protos/google/spanner/v1/type.proto
  src/v1/database_admin_client.js
  src/v1/doc/google/protobuf/doc_duration.js
  src/v1/doc/google/protobuf/doc_struct.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/doc/google/spanner/v1/doc_keys.js
  src/v1/doc/google/spanner/v1/doc_mutation.js
  src/v1/doc/google/spanner/v1/doc_query_plan.js
  src/v1/doc/google/spanner/v1/doc_result_set.js
  src/v1/doc/google/spanner/v1/doc_spanner.js
  src/v1/doc/google/spanner/v1/doc_transaction.js
  src/v1/index.js
  src/v1/instance_admin_client.js
  src/v1/spanner_client.js
  src/v1/spanner_client_config.json
  test/gapic-v1-database-admin.js
  test/gapic-v1-instance-admin.js
  test/gapic-v1.js
Labels: cla: yes

#133 Remove autoCreate for objects that return operations.
  src/database.js
  src/instance.js
  system-test/spanner.js
  test/database.js
  test/instance.js
Labels: cla: yes

#131 format key when deleting cached database
  src/database.js
  test/database.js
Labels: cla: yes

#138 Update region tags in Spanner batch sample.
  samples/batch.js
Labels: cla: no, cla: yes

#141 fix: Clone query passed to encodeQuery
  src/codec.js
  test/codec.js
Labels: cla: yes

#146 chore: remove dead tests
  samples/system-test/spanner.test.js
Labels: cla: yes, testing

#147 testing: remove samples after hook
  samples/system-test/spanner.test.js
Labels: cla: yes, testing

#149 remove circleci fix
  .circleci/config.yml
  samples/package.json
  samples/system-test/util/circleci_wait.js
Labels: cla: yes

#150 test: make sure tests can run in parallel
  samples/package.json
  samples/system-test/spanner.test.js
Labels: cla: no, cla: yes

#155 Upgrade repo-tools and regenerate scaffolding.
  .github/ISSUE_TEMPLATE.md
  .gitignore
  CONTRIBUTORS
  README.md
  package-lock.json
  package.json
  samples/README.md
  samples/package-lock.json
  samples/package.json
Labels: cla: yes

#156 v1.3.0
  package-lock.json
  package.json
  samples/package-lock.json
Labels: cla: yes

#158 chore: setup nighty build in CircleCI
  .circleci/config.yml
  .circleci/get_workflow_name.py
Labels: cla: yes

#160 chore: make samples depend on the current version
  samples/package-lock.json
  samples/package.json
Labels: cla: yes

#159 Update google-auto-auth
  package-lock.json
  package.json
  samples/package-lock.json
Labels: cla: yes

#162 Fix region tags in spanner ref docs.
  src/batch-transaction.js
  src/database.js
Labels: cla: yes

#163 feature: commit timestamp
  src/index.js
  src/v1/spanner_client.js
  system-test/spanner.js
Labels: cla: yes

#165 updating GAPIC v1 code
  package-lock.json
  protos/google/spanner/v1/spanner.proto
  protos/google/spanner/v1/type.proto
  samples/package-lock.json
  src/v1/doc/google/spanner/v1/doc_spanner.js
  src/v1/spanner_client.js
Labels: cla: yes

#166 test: fix get session by name test
  system-test/spanner.js
Labels: cla: yes

#164 1.4.0
  package-lock.json
  package.json
  samples/package-lock.json
  samples/package.json
Labels: cla: yes

#168 chore: workaround for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes

#167 Add Spanner commit timestamp sample.
  samples/system-test/spanner.test.js
  samples/timestamp.js
Labels: cla: no, cla: yes

#169 chore: one more workaround for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes
