Repository googleapis/nodejs-spanner, pull requests merged in 2019-07, with the labels that each got.

#651 fix(deps): upgrade to google-gax 1.x
  package.json
  src/index.ts
  test/index.ts
Labels: cla: yes

#658 docs: add jsdoc for GetPolicyOptions
  src/v1/database_admin_client.js
  src/v1/doc/google/iam/v1/doc_iam_policy.js
  src/v1/doc/google/iam/v1/doc_options.js
  src/v1/instance_admin_client.js
  synth.metadata
Labels: cla: yes

#661 fix(transaction): set/update seqno for all sql requests
  src/transaction.ts
  test/transaction.ts
Labels: cla: yes

#616 chore: release 4.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, status: blocked, type: process

#666 fix(docs): move docs under overloads to be picked up by JSDoc
  src/database.ts
  src/session.ts
  src/table.ts
Labels: cla: yes

#670 chore: release 4.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#672 docs: use the jsdoc-fresh theme
  .jsdoc.js
  package.json
Labels: cla: yes

#673 docs: document apiEndpoint over servicePath
  src/v1/database_admin_client.js
  src/v1/instance_admin_client.js
  src/v1/spanner_client.js
Labels: cla: yes
