Repository googleapis/nodejs-spanner, pull requests merged in 2019-03, with the labels that each got.

#547 chore(deps): use bundled p-queue types
  package.json
  src/session-pool.ts
  test/session-pool.ts
Labels: cla: yes

#549 chore(deps): fix broken dep types
  package.json
  system-test/spanner.ts
Labels: cla: yes

#545 build: update release configuration
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#551 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#550 feat(transaction): batch dml
  protos/google/spanner/v1/spanner.proto
  src/transaction.ts
  src/v1/doc/google/spanner/v1/doc_spanner.js
  src/v1/spanner_client.d.ts
  src/v1/spanner_client.js
  src/v1/spanner_client_config.json
  synth.metadata
  system-test/spanner.ts
  test/transaction.ts
Labels: cla: yes

#544 docs: Update grammar
  src/transaction.ts
Labels: cla: yes

#552 Release @google-cloud/spanner v3.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#554 test: add install tests and fix issues
  package.json
  src/index.ts
  src/instance.ts
  src/session-pool.ts
  system-test/fixtures/sample/package.json
  system-test/fixtures/sample/src/index.ts
  system-test/fixtures/sample/tsconfig.json
  system-test/install.ts
  system-test/spanner.ts
  test/index.ts
  test/session-pool.ts
Labels: cla: yes

#556 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#563 docs: update jsdoc samples and update json import paths
  src/v1/database_admin_client.js
  src/v1/instance_admin_client.js
  src/v1/spanner_client.js
  synth.metadata
Labels: cla: yes

#565 docs: use backticks for JS values
  src/v1/doc/google/longrunning/doc_operations.js
  synth.metadata
Labels: cla: yes

#564 tests: correctly sort latencies
  benchmark/ycsb.js
Labels: cla: yes

#566 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#568 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#571 docs(samples): Add Cloud Spanner Batch DML sample
  samples/dml.js
  samples/system-test/spanner.test.js
Labels: automerge, cla: yes

#573 fix: include 'x-goog-request-params' header in requests
  src/v1/database_admin_client.js
  src/v1/instance_admin_client.js
  src/v1/spanner_client.js
  synth.metadata
Labels: cla: yes
