Repository googleapis/nodejs-spanner, pull requests merged in 2019-04, with the labels that each got.

#575 refactor: use execSync for tests
  samples/package.json
  samples/system-test/spanner.test.js
Labels: automerge, cla: yes, kokoro:force-run

#576 refactor: wrap execSync with encoding: utf-8
  samples/system-test/spanner.test.js
Labels: cla: yes, unrelated-ci-failure

#580 tests: add tests to increase code coverage
  src/codec.ts
  test/batch-transaction.ts
  test/database.ts
  test/session-pool.ts
  test/transaction.ts
Labels: :rotating_light:, cla: yes

#585 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes
