Repository googleapis/nodejs-spanner, pull requests merged in 2019-02, with the labels that each got.

#511 docs: fix example comments
  src/v1/database_admin_client.js
  src/v1/instance_admin_client.js
  src/v1/spanner_client.js
  synth.metadata
Labels: cla: yes

#512 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#514 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#515 docs: update contributing path in README
  README.md
Labels: cla: yes

#506 breaking: refactor(transaction): split logic into new classes
  package.json
  samples/dml.js
  samples/transaction.js
  src/batch-transaction.ts
  src/codec.ts
  src/database.ts
  src/index.ts
  src/partial-result-stream.ts
  src/session-pool.ts
  src/session.ts
  src/table.ts
  src/transaction-request.ts
  src/transaction-runner.ts
  src/transaction.ts
  src/v1/spanner_client.d.ts
  system-test/spanner.ts
  test/batch-transaction.ts
  test/codec.ts
  test/database.ts
  test/session-pool.ts
  test/session.ts
  test/table.ts
  test/transaction-request.ts
  test/transaction-runner.ts
  test/transaction.ts
Labels: :rotating_light:, cla: yes, semver: major

#508 refactor(types): enable noImplicitAny in session-pool.ts
  package.json
  proto/spanner.d.ts
  proto/spanner_database_admin.d.ts
  proto/spanner_instance_admin.d.ts
  src/session-pool.ts
  src/session.ts
  test/session-pool.ts
Labels: :rotating_light:, cla: yes

#516 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes, kokoro:force-run

#519 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#525 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#523 build: use linkinator for docs test
  package.json
Labels: cla: yes

#522 fix: throw on invalid credentials
  src/v1/database_admin_client.js
  src/v1/instance_admin_client.js
  src/v1/spanner_client.js
  synth.metadata
Labels: cla: yes

#503 Add spanner_grpc_config.json and enable grpc-gcp support for spanner
  src/index.ts
  src/spanner_grpc_config.json
  test/index.ts
  tsconfig.json
Labels: :rotating_light:, cla: yes

#533 Fixed example for Table.upsert()
  src/table.ts
Labels: cla: yes

#534 chore: temporarily disable gts
  package.json
Labels: cla: yes

#540 fix(transaction): re-use session in transaction runners
  src/database.ts
  src/transaction-runner.ts
  test/database.ts
  test/transaction-runner.ts
Labels: cla: yes

#517 feat(timestamp): create new date/timestamp classes
  package.json
  src/batch-transaction.ts
  src/codec.ts
  src/index.ts
  src/transaction.ts
  system-test/spanner.ts
  test/batch-transaction.ts
  test/codec.ts
  test/index.ts
  test/transaction.ts
Labels: :rotating_light:, cla: yes

#541 Release @google-cloud/spanner v3.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#543 chore: update proto docs and code style
  protos/google/spanner/admin/database/v1/spanner_database_admin.proto
  protos/google/spanner/admin/instance/v1/spanner_instance_admin.proto
  protos/google/spanner/v1/keys.proto
  protos/google/spanner/v1/mutation.proto
  protos/google/spanner/v1/query_plan.proto
  protos/google/spanner/v1/result_set.proto
  protos/google/spanner/v1/spanner.proto
  protos/google/spanner/v1/transaction.proto
  protos/google/spanner/v1/type.proto
  src/v1/database_admin_client.js
  src/v1/doc/google/rpc/doc_status.js
  src/v1/doc/google/spanner/admin/database/v1/doc_spanner_database_admin.js
  src/v1/doc/google/spanner/admin/instance/v1/doc_spanner_instance_admin.js
  src/v1/doc/google/spanner/v1/doc_keys.js
  src/v1/doc/google/spanner/v1/doc_mutation.js
  src/v1/doc/google/spanner/v1/doc_query_plan.js
  src/v1/doc/google/spanner/v1/doc_result_set.js
  src/v1/doc/google/spanner/v1/doc_spanner.js
  src/v1/doc/google/spanner/v1/doc_transaction.js
  src/v1/doc/google/spanner/v1/doc_type.js
  src/v1/instance_admin_client.js
  src/v1/spanner_client.js
  synth.metadata
Labels: cla: yes
