Repository googleapis/nodejs-spanner, pull requests merged in 2019-05, with the labels that each got.

#588 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#587 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#589 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#594 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes

#595 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#596 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#598 fix: DEADLINE_EXCEEDED is no longer retried
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  src/v1/database_admin_client.js
  src/v1/database_admin_client_config.json
  src/v1/doc/google/iam/v1/doc_iam_policy.js
  src/v1/doc/google/iam/v1/doc_policy.js
  src/v1/doc/google/protobuf/doc_any.js
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/doc/google/type/doc_expr.js
  src/v1/instance_admin_client.js
  src/v1/instance_admin_client_config.json
  src/v1/spanner_client_config.json
  synth.metadata
Labels: cla: yes

#605 fix(docs): add google.type namespace
  src/index.ts
Labels: cla: yes

#609 docs(samples): Add queryWithParameter to Cloud Spanner sample.
  samples/dml.js
  samples/system-test/spanner.test.js
Labels: cla: yes

#602 fix: treat deadline errors as idempotent
  src/v1/database_admin_client_config.json
  src/v1/instance_admin_client_config.json
  synth.metadata
Labels: cla: yes

#603 docs: use new keyword in client invocation
  README.md
Labels: automerge, cla: yes

#612 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#617 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/database_admin_client.js
  src/v1/instance_admin_client.js
  src/v1/spanner_client.js
  synth.metadata
Labels: cla: yes

#623 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#625 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#628 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#631 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#632 build: remove verbose logging from cleanup.sh
  .kokoro/cleanup.sh
Labels: cla: yes
