Repository googleapis/nodejs-spanner, pull requests merged in 2020-07, with the labels that each got.

#1169 build: use bazel build
  src/v1/instance_admin_client.ts
  synth.metadata
  synth.py
  test/gapic_instance_admin_v1.ts
Labels: automerge, cla: yes

#1170 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#1171 test: change system-test setup against emulator
  .github/workflows/system-tests-against-emulator.sh
  .github/workflows/system-tests-against-emulator.yaml
Labels: cla: yes

#1167 perf: increase default min sessions to 25
  src/session-pool.ts
  test/session-pool.ts
  test/spanner.ts
Labels: cla: yes

#1168 fix: remove error listener to prevent memory leak
  src/session-pool.ts
Labels: cla: yes

#1172 chore(deps): update dependency p-limit to v3
  package.json
  samples/package.json
  system-test/spanner.ts
Labels: automerge, cla: yes

#1176 chore: re-generated to pick up changes from self
  protos/google/spanner/admin/database/v1/spanner_database_admin.proto
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#1178 chore: fix typo in .gitattributes
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#1175 chore: update samples cleanup
  samples/system-test/spanner.test.js
Labels: automerge, cla: yes

#1181 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#1188 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#1187 refactor(test): use exponential backoff and retry a sample test
  samples/system-test/spanner.test.js
Labels: cla: yes

#1189 feat: Spanner numeric type, add Node 8 tests
  protos/google/spanner/v1/type.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: partial

#1194 fix(spanner): update UpdateBackup to be retryable
  src/v1/database_admin_client_config.json
  synth.metadata
Labels: cla: yes, context: full

#1192 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: cla: yes

#1190 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#1195 build: rename _toc to toc, move gittatributes files to node templates
  .gitattributes
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#1202 build: config for new ref docs
  .kokoro/release/docs-devsite.cfg
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial
