Repository googleapis/nodejs-spanner, pull requests merged in 2020-10, with the labels that each got.

#1246 test: skip tests that filter on get operations
  samples/system-test/spanner.test.js
  system-test/spanner.ts
Labels: api: spanner, cla: yes

#1247 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#1248 test: unskip "should list database operations"
  samples/system-test/spanner.test.js
Labels: cla: yes

#1228 fix: do not create sessions after getDatabases call
  src/instance.ts
  test/instance.ts
  test/spanner.ts
Labels: api: spanner, cla: yes

#1249 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: spanner, automerge: exact, cla: yes, context: full

#1255 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1256 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1259 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
  test/instance.ts
  test/spanner.ts
Labels: automerge, cla: yes, context: full
