Repository googleapis/nodejs-spanner, pull requests merged in 2020-05, with the labels that each got.

#928 refactor: use @grpc/grpc-js v1.0.x and grpc-gcp v0.3.x
  bin/benchwrapper.js
  bin/benchwrapper_test_client.js
  package.json
  samples/package.json
  src/backup.ts
  src/common-grpc/service.ts
  src/common.ts
  src/database.ts
  src/index.ts
  src/instance.ts
  src/partial-result-stream.ts
  src/session-pool.ts
  src/session.ts
  src/transaction-runner.ts
  src/transaction.ts
  system-test/spanner.ts
  test/backup.ts
  test/common/service.ts
  test/database.ts
  test/index.ts
  test/instance.ts
  test/mockserver/mockdatabaseadmin.ts
  test/mockserver/mockinstanceadmin.ts
  test/mockserver/mockspanner.ts
  test/partial-result-stream.ts
  test/session.ts
  test/spanner.ts
  test/transaction-runner.ts
  test/transaction.ts
Labels: cla: yes

#937 feat: check status of long running operation by its name
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  synth.metadata
  test/gapic_database_admin_v1.ts
  test/gapic_instance_admin_v1.ts
  test/gapic_spanner_v1.ts
Labels: automerge, cla: yes

#923 fix: use DELETE FROM for consistency
  samples/dml.js
Labels: api: spanner, cla: yes

#955 fix: delete old instances then create new instance
  samples/system-test/spanner.test.js
Labels: api: spanner, cla: yes

#957 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#933 fix: skip some tests when run against the emulator
  system-test/spanner.ts
Labels: cla: yes

#925 fix(types)!: properly format listing methods with gaxOptions
  package.json
  src/common.ts
  src/database.ts
  src/index.ts
  src/instance.ts
  system-test/spanner.ts
  test/database.ts
  test/index.ts
  test/instance.ts
  test/spanner.ts
Labels: cla: yes

#798 feat: expose displayName in createInstance
  src/index.ts
  test/index.ts
Labels: cla: yes

#959 chore: improve system-tests
  src/backup.ts
  system-test/spanner.ts
Labels: cla: yes

#961 chore: improve samples-test
  samples/package.json
  samples/system-test/spanner.test.js
Labels: cla: yes

#962 chore: re-generated to pick up changes from self
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#966 test: run system tests against the emulator
  .github/workflows/system-tests-against-emulator.sh
  .github/workflows/system-tests-against-emulator.yaml
Labels: api: spanner, cla: yes

#948 chore: cleanup eslint configs
  samples/.eslintrc.yml
  scripts/.eslintrc.yml
  src/.eslintrc.yml
  test/.eslintrc.yml
Labels: cla: yes

#963 feat: increase sessions in the pool in batches
  .gitignore
  benchmark/spanner.ts
  samples/system-test/spanner.test.js
  src/session-pool.ts
  system-test/spanner.ts
  test/mockserver/mockspanner.ts
  test/session-pool.ts
  test/spanner.ts
  tsconfig.json
Labels: cla: yes

#1030 fix: always clean up stale instances if any
  system-test/spanner.ts
Labels: cla: yes

#1032 chore: update grpc config files to be consistent
  src/v1/database_admin_client_config.json
  src/v1/instance_admin_client_config.json
  src/v1/spanner_client_config.json
  synth.metadata
Labels: cla: yes, context: full

#1060 chore: remove .idea from .gitignore
  .gitignore
Labels: cla: yes, context: none
