Repository googleapis/nodejs-spanner, pull requests merged in 2020-11, with the labels that each got.

#1262 test: fix NUMERIC toJSON test expectation
  test/codec.ts
Labels: api: spanner, cla: yes

#1264 fix: do not modify options object, use defaultScopes
  .kokoro/trampoline_v2.sh
  package.json
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  src/v1/spanner_client.ts
  synth.metadata
Labels: api: spanner, automerge, cla: yes

#1261 test: unskip tests that filter on get operations
  samples/system-test/spanner.test.js
  system-test/spanner.ts
Labels: api: spanner, cla: yes

#1260 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#1269 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  src/v1/spanner_client.ts
  synth.metadata
Labels: api: spanner, cla: yes, context: none

#1270 build: stop tracking generated files
  src/backup.ts
  src/database.ts
  src/instance.ts
  src/session.ts
  src/transaction.ts
  synth.metadata
  test/transaction-runner.ts
Labels: api: spanner, cla: yes, context: none

#1273 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#1275 types: fix lint issue
  synth.metadata
  test/transaction-runner.ts
Labels: api: spanner, cla: yes, context: none

#1276 fix(deps): remove @types/big.js from dev dependencies
  package.json
Labels: api: spanner, cla: yes
