Repository googleapis/nodejs-spanner, pull requests merged in 2020-06, with the labels that each got.

#936 fix: pause request stream on backpressure
  .gitignore
  src/partial-result-stream.ts
  src/transaction.ts
  test/mockserver/mockspanner.ts
  test/partial-result-stream.ts
  test/spanner.ts
  test/transaction.ts
Labels: cla: yes

#1070 feat: support callbacks for exists(), getState(), getExpireTime() methods
  src/backup.ts
  test/backup.ts
Labels: cla: yes

#1073 feat: add code sample for creating an instance
  samples/instance.js
  samples/system-test/spanner.test.js
Labels: cla: yes

#1072 fix: update DELETE samples to match docs
  samples/crud.js
  samples/system-test/spanner.test.js
Labels: cla: yes

#1074 chore: re-generated to pick up changes from self
  .gitignore
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#1082 chore: update backup module and backup unit tests
  src/backup.ts
  test/backup.ts
Labels: cla: yes

#1081 chore: re-generated to pick up changes from self
  README.md
  protos/protos.js
  samples/README.md
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  src/v1/spanner_client.ts
  synth.metadata
Labels: cla: yes, context: none

#1031 perf: use write fraction when resizing pool
  benchmark/spanner.ts
  src/session-pool.ts
  system-test/spanner.ts
  test/session-pool.ts
  test/spanner.ts
Labels: api: spanner, cla: yes

#1094 fix: set instanceId to the given id
  src/index.ts
  test/spanner.ts
Labels: cla: yes

#1092 feat(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#1121 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1050 chore: add gaxOptions
  src/database.ts
  src/index.ts
  src/instance.ts
  src/session.ts
  src/table.ts
  src/transaction.ts
  test/database.ts
  test/index.ts
  test/instance.ts
  test/session.ts
  test/table.ts
  test/transaction.ts
Labels: cla: yes

#1145 fix: set displayName in CreateInstance sample
  samples/instance.js
Labels: cla: yes

#1146 fix: handle fallback option properly
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  src/v1/spanner_client.ts
  synth.metadata
Labels: automerge, cla: yes, context: none

#1150 fix: unskip PDML tests when run against emulator
  .github/workflows/system-tests-against-emulator.sh
  system-test/spanner.ts
Labels: cla: yes

#1153 chore(system/samples-test): lower the age of old instances to 4 hours
  samples/system-test/spanner.test.js
  system-test/spanner.ts
Labels: cla: yes

#1155 docs: explain invalid TimestampBounds params
  src/database.ts
Labels: cla: yes

#1156 fix(samples-test): race condition in deleteData sample
  samples/crud.js
Labels: cla: yes

#1149 chore: retry flaky tests for exceed administrative requests per minute quota error
  system-test/spanner.ts
Labels: cla: yes

#1157 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#1159 fix: race condition in "should transfer value from one record to another using DML statements within a transaction test"
  samples/dml.js
Labels: cla: yes

#1148 chore: set Ruby namespace in proto options
  protos/google/spanner/admin/database/v1/backup.proto
  protos/google/spanner/admin/database/v1/common.proto
  protos/google/spanner/admin/database/v1/spanner_database_admin.proto
  protos/google/spanner/admin/instance/v1/spanner_instance_admin.proto
  protos/google/spanner/v1/keys.proto
  protos/google/spanner/v1/mutation.proto
  protos/google/spanner/v1/query_plan.proto
  protos/google/spanner/v1/result_set.proto
  protos/google/spanner/v1/spanner.proto
  protos/google/spanner/v1/transaction.proto
  protos/google/spanner/v1/type.proto
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: partial

#1161 chore: retry tests in "before all" and "after all" hooks
  samples/system-test/spanner.test.js
  system-test/spanner.ts
Labels: cla: yes

#1166 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#1164 chore: create instance sample
  samples/system-test/spanner.test.js
Labels: cla: yes
