Repository googleapis/nodejs-spanner, pull requests merged in 2020-08, with the labels that each got.

#1204 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#1206 feat: accept gaxOptions in Database and Session #delete()
  src/database.ts
  src/session.ts
  test/database.ts
  test/session.ts
Labels: cla: yes

#1211 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1199 feat: return full nextQuery object in paginated calls
  samples/backups-get.js
  src/database.ts
  src/index.ts
  src/instance.ts
  test/database.ts
  test/index.ts
  test/instance.ts
Labels: cla: yes

#1205 fix: retry PDML on Aborted and Internal errors
  src/database.ts
  src/partial-result-stream.ts
  test/database.ts
  test/mockserver/mockspanner.ts
  test/spanner.ts
Labels: cla: yes

#1213 fix: update minimum gax version to 2.7.0
  package.json
Labels: cla: yes

#1216 chore: add retry options to flaky system tests
  system-test/spanner.ts
Labels: cla: yes

#1217 build: use gapic-generator-typescript v1.0.7.
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  src/v1/spanner_client.ts
  synth.metadata
Labels: automerge, cla: yes, context: full

#1207 fix: batch transaction should use a session from the pool
  src/batch-transaction.ts
  src/database.ts
  test/batch-transaction.ts
  test/database.ts
  test/spanner.ts
Labels: cla: yes

#1218 build: perform publish using Node 12, update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1222 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#1210 docs: sample on setting per-request gaxOptions
  samples/dml.js
  samples/system-test/spanner.test.js
Labels: api: spanner, cla: yes

#1208 fix: handle potential errors when creating stream
  src/transaction.ts
  test/spanner.ts
  test/transaction.ts
Labels: api: spanner, cla: yes

#1224 build: move system and samples test from Node 10 to Node 12
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#1196 feat: add resource header prefix
  src/backup.ts
  src/batch-transaction.ts
  src/common.ts
  src/database.ts
  src/index.ts
  src/instance.ts
  src/session.ts
  src/transaction.ts
  test/backup.ts
  test/batch-transaction.ts
  test/database.ts
  test/index.ts
  test/instance.ts
  test/session.ts
  test/transaction.ts
Labels: api: spanner, cla: yes

#1198 feat: set metadata during getBackups and getMetadata calls
  src/backup.ts
  src/database.ts
  src/instance.ts
  src/session.ts
  test/backup.ts
  test/database.ts
  test/instance.ts
  test/session.ts
Labels: api: spanner, cla: yes

#1226 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
