Repository googleapis/nodejs-spanner, pull requests merged in 2020-04, with the labels that each got.

#880 build: set AUTOSYNTH_MULTIPLE_COMMITS=true for context aware commits
  synth.py
Labels: automerge, cla: yes

#857 feat: run and runStream can return query stats
  src/database.ts
  src/v1/spanner_client.d.ts
  test/mockserver/mockspanner.ts
  test/spanner.ts
Labels: api: spanner, cla: yes

#886 chore: remove duplicate mocha config
  .mocharc.json
Labels: automerge, cla: yes

#897 fix: remove eslint, update gax, fix generated protos, run the generator
  package.json
  protos/protos.json
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#899 build: remove unused codecov config
  codecov.yaml
Labels: automerge, cla: yes

#901 fix: remove typescript conversion leftovers
  src/v1/index.js
Labels: cla: yes

#902 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#903 chore: remove tslint.json
  tslint.json
Labels: automerge, cla: yes

#879 fix: remove src/common-grpc/operation.ts
  src/common-grpc/operation.ts
  src/index.ts
  test/common/operation.ts
  test/index.ts
Labels: automerge, cla: yes

#908 chore: remove unused dev packages
  package.json
Labels: automerge, cla: yes

#781 feat!: add typings for top level object
  .gitignore
  src/index.ts
  src/instance.ts
  system-test/spanner.ts
  test/index.ts
  test/spanner.ts
Labels: cla: yes, semver: major

#915 chore: run fix instead of lint in synthfile
  synth.py
Labels: automerge, cla: yes

#916 chore: linting
  .gitignore
  protos/google/spanner/admin/database/v1/backup.proto
  protos/protos.json
  samples/timestamp.js
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  synth.metadata
  system-test/spanner.ts
  test/gapic_database_admin_v1.ts
  test/index.ts
  test/instance.ts
  test/spanner.ts
  test/transaction-runner.ts
  test/transaction.ts
Labels: automerge, cla: yes

#855 feat: spanner backup and restore support
  package.json
  samples/backups-cancel.js
  samples/backups-create.js
  samples/backups-delete.js
  samples/backups-get-database-operations.js
  samples/backups-get-operations.js
  samples/backups-get.js
  samples/backups-restore.js
  samples/backups-update.js
  samples/backups.js
  samples/package.json
  samples/system-test/spanner.test.js
  src/backup.ts
  src/database.ts
  src/index.ts
  src/instance.ts
  system-test/spanner.ts
  test/backup.ts
  test/database.ts
  test/index.ts
  test/instance.ts
  test/mockserver/mockdatabaseadmin.ts
  test/spanner.ts
Labels: cla: yes

#917 build: use codecov's action, now that it's authless (#499)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes

#918 chore: update README to include backups samples
  README.md
  samples/README.md
  synth.metadata
Labels: automerge, cla: yes

#919 build: adopt changes to generator formatting
  protos/protos.js
  synth.metadata
Labels: cla: yes

#805 fix(types)!: types for createInstance
  src/index.ts
  src/instance.ts
  test/index.ts
Labels: cla: yes

#920 docs: update jsdoc annotations
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  synth.metadata
Labels: cla: yes

#921 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes

#930 fix: update spanner package in sample
  samples/package.json
Labels: cla: yes
