Repository googleapis/nodejs-spanner, pull requests merged in 2021-05, with the labels that each got.

#1358 test: enable numeric integration tests on emulator
  system-test/spanner.ts
Labels: api: spanner, automerge, cla: yes

#1359 deps: bump google-gax to latest
  package.json
Labels: api: spanner, automerge, cla: yes

#1355 samples: added comments for timeout settings
  samples/dml.js
Labels: api: spanner, cla: yes, samples

#1372 chore: fix lint issue
  samples/backups-get-database-operations.js
  samples/backups-get-operations.js
  samples/database-create-with-encryption-key.js
  samples/database-create-with-version-retention-period.js
  samples/dml.js
  src/backup.ts
  src/database.ts
  src/index.ts
  src/instance.ts
  src/session.ts
  src/transaction.ts
  src/v1/database_admin_client.ts
  src/v1/instance_admin_client.ts
  src/v1/spanner_client.ts
  system-test/install.ts
  system-test/spanner.ts
  test/backup.ts
  test/batch-transaction.ts
  test/codec.ts
  test/common/service.ts
  test/database.ts
  test/gapic_database_admin_v1.ts
  test/gapic_instance_admin_v1.ts
  test/gapic_spanner_v1.ts
  test/index.ts
  test/instance.ts
  test/partial-result-stream.ts
  test/session-pool.ts
  test/spanner.ts
  test/table.ts
  test/transaction.ts
Labels: api: spanner, cla: yes

#1371 fix: ensure table funcs accept gaxOptions directly
  src/table.ts
  test/table.ts
Labels: api: spanner, cla: yes

#1379 docs: align timeout values with documentation
  samples/dml.js
Labels: api: spanner, cla: yes

#1380 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  owlbot.py
  synth.metadata
  synth.py
  test/mockserver/mockinstanceadmin.ts
Labels: api: spanner, cla: yes
