Repository googleapis/nodejs-spanner, pull requests merged in 2021-04, with the labels that each got.

#1332 fix: prevent unhandled promise rejections while creating session
  src/session-pool.ts
  test/session-pool.ts
Labels: api: spanner, cla: yes

#1335 feat: regenerate protos with new types
  package.json
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/extra_proto_list.json
Labels: api: spanner, automerge, cla: yes

#1282 feat: support RPC priority
  .gitignore
  samples/rpc-priority.js
  samples/system-test/spanner.test.js
  src/index.ts
  src/transaction.ts
  synth.metadata
  test/database.ts
  test/mockserver/mockspanner.ts
  test/spanner.ts
  test/table.ts
  test/transaction.ts
Labels: api: spanner, cla: yes

#1340 fix: prevent unhandled promise rejection while projectId or credential not found
  src/session-pool.ts
  test/session-pool.ts
Labels: api: spanner, cla: yes

#1341 chore: re-generated to pick up changes from self
  .gitignore
  README.md
  samples/README.md
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: none

#1345 chore: re-generated to pick up changes from googleapis
  protos/google/spanner/admin/database/v1/backup.proto
  protos/google/spanner/admin/database/v1/common.proto
  protos/google/spanner/admin/database/v1/spanner_database_admin.proto
  protos/google/spanner/v1/commit_response.proto
  protos/google/spanner/v1/spanner.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/database_admin_client.ts
  src/v1/spanner_proto_list.json
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: partial

#1346 chore: re-generated to pick up changes from synthtool
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: partial

#1348 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#1344 chore: add default assignee for issues
  .github/blunderbuss.yml
Labels: api: spanner, cla: yes

#1338 test: enable rpc prio test
  samples/rpc-priority.js
  samples/system-test/spanner.test.js
Labels: api: spanner, cla: yes

#1352 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#1354 chore: re-generated to pick up changes from self
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
