Repository googleapis/nodejs-spanner, pull requests merged in 2021-06, with the labels that each got.

#1382 docs: add missing JSDoc for table API
  src/table.ts
  src/transaction.ts
Labels: api: spanner, cla: yes

#1225 feat: support setting `optimizerStatisticsPackage`
  samples/queryoptions.js
  src/database.ts
  test/spanner.ts
Labels: api: spanner, automerge, cla: yes

#1384 docs: improve docs for gaxoptions
  src/backup.ts
  src/batch-transaction.ts
  src/database.ts
  src/index.ts
  src/instance.ts
  src/session.ts
  src/table.ts
  src/transaction.ts
Labels: api: spanner, cla: yes

#1388 fix: unknown errors should not be retried
  src/transaction-runner.ts
  test/transaction-runner.ts
Labels: api: spanner, cla: yes

#1395 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: spanner, automerge, cla: yes

#1397 fix: reset buffered chunked value before retry
  src/partial-result-stream.ts
  test/mockserver/mockspanner.ts
  test/spanner.ts
Labels: api: spanner, cla: yes

#1402 docs: fix the broken link and improve jsdocs
  src/backup.ts
  src/batch-transaction.ts
  src/database.ts
  src/index.ts
  src/instance.ts
  src/table.ts
  src/transaction.ts
Labels: api: spanner, automerge, cla: yes

#1409 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: spanner, cla: yes

#1347 samples: indexing samples conform to rubric
  samples/index-create-storing.js
  samples/index-create.js
  samples/index-query-data.js
  samples/index-read-data-with-storing.js
  samples/index-read-data.js
  samples/system-test/spanner.test.js
  src/database.ts
  src/table.ts
Labels: api: spanner, automerge, cla: yes, owlbot:ignore, samples

#1407 fix: replace projectId placeholder in formatted names
  README.md
  samples/README.md
  src/index.ts
  test/index.ts
  test/mockserver/mockspanner.ts
  test/spanner.ts
Labels: api: spanner, automerge, cla: yes
