Repository googleapis/nodejs-spanner, pull requests merged in 2022-09, with the labels that each got.

#1703 fix: test case fix to avoid the latest typescript dependency issue
  test/database.ts
Labels: api: spanner, size: xs

#1704 fix: move runtime dependencies from dev dependencies to dependencies
  package.json
Labels: api: spanner, size: xs

#1710 fix(deps): use grpc-gcp v1.0.0
  package.json
Labels: automerge, api: spanner, size: xs

#1611 feat: support customer managed instance configurations
  src/index.ts
  src/instance-config.ts
  system-test/spanner.ts
  test/index.ts
  test/instance-config.ts
Labels: automerge, api: spanner, size: xl
