Repository googleapis/nodejs-spanner, pull requests merged in 2023-05, with the labels that each got.

#1842 doc: Leader aware routing
  src/index.ts
Labels: api: spanner, size: xs

#1847 fix: set grpc useragent
  src/common-grpc/service.ts
  test/common/service.ts
Labels: api: spanner, size: s

#1844 docs: Update `SessionPoolOptions` typings using current defaults
  src/session-pool.ts
Labels: api: spanner, size: xs

#1802 feat: add support for UpdateDatabase
  README.md
  samples/README.md
  samples/database-update.js
  samples/system-test/spanner.test.js
  src/database.ts
  system-test/spanner.ts
  test/database.ts
Labels: api: spanner, size: l

#1854 chore: dev containers
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/postCreate.sh
  .kokoro/release/docs-devsite.sh
Labels: automerge, api: spanner, size: s
