Repository googleapis/nodejs-spanner, pull requests merged in 2024-11, with the labels that each got.

#2175 chore: support for option multiplexed in create session
  src/database.ts
  test/database.ts
Labels: automerge, api: spanner, size: s

#2182 build(revert): configure release builds using multi-scm
  .github/.OwlBot.lock.yaml
  .github/release-trigger.yml
  .github/workflows/ci.yaml
  .kokoro/common.cfg
  .kokoro/continuous/node18/common.cfg
  .kokoro/continuous/node18/lint.cfg
  .kokoro/continuous/node18/samples-test.cfg
  .kokoro/continuous/node18/system-test.cfg
  .kokoro/continuous/node18/test.cfg
  .kokoro/presubmit/node18/common.cfg
  .kokoro/presubmit/node18/samples-test.cfg
  .kokoro/presubmit/node18/system-test.cfg
  .kokoro/presubmit/node18/test.cfg
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/system-test.sh
  .kokoro/test.bat
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, api: spanner, size: m

#2184 fix: Span events Issue 2166
  src/database.ts
Labels: automerge, kokoro:run, api: spanner, size: s

#2187 chore: Release fix
  .github/release-trigger.yml
  owlbot.py
Labels: automerge, api: spanner, size: xs

#2190 chore(samples): Add samples for Cloud Spanner Default Backup Schedules
  README.md
  samples/README.md
  samples/create-instance-without-default-backup-schedules.js
  samples/system-test/spanner.test.js
  samples/update-instance-default-backup-schedule-type.js
Labels: api: spanner, samples, size: m
