Repository googleapis/nodejs-spanner, pull requests merged in 2024-09, with the labels that each got.

#2108 build: fix path-to-regexp
  .gitignore
  package.json
Labels: kokoro:force-run, automerge, api: spanner, size: xs

#2105 observability: ensure that each span has otel.scope.name,version
  observability-test/observability.ts
  src/instrument.ts
Labels: api: spanner, size: s

#2101 observability: add SessionPool span annotations
  observability-test/observability.ts
  package.json
  src/database.ts
  src/session-pool.ts
  src/transaction.ts
  test/session-pool.ts
  test/spanner.ts
Labels: automerge, api: spanner, size: l

#2115 feat: (observability) add spans for BatchTransaction and Table
  observability-test/batch-transaction.ts
  observability-test/table.ts
  src/batch-transaction.ts
  src/instrument.ts
  src/table.ts
  src/transaction.ts
  test/session-pool.ts
Labels: automerge, api: spanner, size: l

#2117 chore(samples): Add samples for Cloud Spanner Scheduled Backups
  README.md
  samples/README.md
  samples/create-full-backup-schedule.js
  samples/create-incremental-backup-schedule.js
  samples/delete-backup-schedule.js
  samples/get-backup-schedule.js
  samples/list-backup-schedules.js
  samples/system-test/spanner.test.js
  samples/update-backup-schedule.js
Labels: automerge, api: spanner, samples, size: l

#2133 observability: dynamically retrieve TRACER_VERSION from published package.json
  observability-test/observability.ts
  src/instrument.ts
Labels: automerge, api: spanner, size: xs

#2119 feat(observability): trace Database methods
  observability-test/database.ts
  observability-test/spanner.ts
  observability-test/table.ts
  src/database.ts
  src/instrument.ts
  test/database.ts
  test/spanner.ts
Labels: automerge, api: spanner, size: xl
