Repository googleapis/nodejs-spanner, pull requests merged in 2025-08, with the labels that each got.

#2380 fix: provide option to disable built in metrics
  .github/workflows/ci.yaml
  .github/workflows/issues-no-repro.yaml
  .github/workflows/response.yaml
  src/index.ts
  test/index.ts
  test/metrics/metrics.ts
Labels: api: spanner, size: s

#2391 chore: enable integration test against mux as required
  .github/sync-repo-settings.yaml
Labels: api: spanner, size: xs

#2393 docs: add comments on the r/w transaction sample
  samples/transaction.js
Labels: api: spanner, samples, size: xs

#2388 feat(spanner): support setting read lock mode
  src/database.ts
  src/index.ts
  src/table.ts
  src/transaction-runner.ts
  src/transaction.ts
  system-test/spanner.ts
  test/database.ts
  test/index.ts
  test/spanner.ts
  test/table.ts
  test/transaction-runner.ts
  test/transaction.ts
Labels: api: spanner, size: l

#2405 README: update readme for multiplexed sessions
  .github/workflows/ci.yaml
  .github/workflows/issues-no-repro.yaml
  .readme-partials.yml
  README.md
Labels: api: spanner, size: s
