Repository googleapis/nodejs-spanner, pull requests merged in 2025-01, with the labels that each got.

#2209 fix: remove default global trace context propagator
  src/index.ts
  src/instrument.ts
Labels: automerge, api: spanner, size: s

#2215 feat: add gcp client attributes for Opentelemetry traces
  observability-test/observability.ts
  src/instrument.ts
Labels: automerge, api: spanner, size: s

#2217 test: fix flake system tests
  system-test/spanner.ts
Labels: api: spanner, size: m

#2219 chore: Use Enterprise edition for autoscaler instances
  samples/instance-with-autoscaling-config.js
Labels: automerge, api: spanner, size: xs

#2222 chore(spanner): Update CODEOWNERS to use TeamSync Managed Team
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: spanner, size: xs
